// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjCV6womsXCSGklUei46Kq1z8ICWtu5K0',
    appId: '1:16837897194:web:a4ee7986b1cc29eac8e093',
    messagingSenderId: '16837897194',
    projectId: 'contact-trace-f32b4',
    authDomain: 'contact-trace-f32b4.firebaseapp.com',
    storageBucket: 'contact-trace-f32b4.firebasestorage.app',
    measurementId: 'G-C7NWKES07C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCivseU5vtgqhiPLqkF67u7V21OMD4Jgi8',
    appId: '1:16837897194:android:526ca4add3ac0fd9c8e093',
    messagingSenderId: '16837897194',
    projectId: 'contact-trace-f32b4',
    storageBucket: 'contact-trace-f32b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA7xNYGyww-TLfXb-DkzQQkjH0bSra11c',
    appId: '1:1072763499211:ios:84de9f89093aef3d08614e',
    messagingSenderId: '1072763499211',
    projectId: 'contact-tracing-856d6',
    storageBucket: 'contact-tracing-856d6.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA7xNYGyww-TLfXb-DkzQQkjH0bSra11c',
    appId: '1:1072763499211:ios:84de9f89093aef3d08614e',
    messagingSenderId: '1072763499211',
    projectId: 'contact-tracing-856d6',
    storageBucket: 'contact-tracing-856d6.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlvTU2wv2ghoSdyfeti5Ix98q6g6RNXc4',
    appId: '1:1072763499211:web:9a64be71050670a008614e',
    messagingSenderId: '1072763499211',
    projectId: 'contact-tracing-856d6',
    authDomain: 'contact-tracing-856d6.firebaseapp.com',
    storageBucket: 'contact-tracing-856d6.firebasestorage.app',
  );
}